---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: ${namespace}
spec:
  secretName: wildcard-tls
  dnsNames:
    - "${local.user_domain}"
    - "*.${local.user_domain}"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
