---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: ${namespace}
spec:
  secretName: wildcard-tls
  dnsNames:
    - "${username}.${coder_domain}"
    - "*.${username}.${coder_domain}"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
